### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by miharekar** [endocrimes/twentysix#2]
First, thanks for this gem!

I've been using it for a while but lately this has been happening on `client.create_transfer` calls:

```
<HTTParty::Response:0x192b430 parsed_response={"title"=>"Update Required", "message"=>"Please update your app in order to continue to use this feature."}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>…
```

Any clue what's going on? I can make a PR if you know what needs fixing 😅

**Comment by endocrimes** [comment]
@mrfoto Thanks for the issue, sorry for the slow reply, I was at a team offsite in Miami last week.

I'll scrape the API again next time I need to make a transfer, but if you do one on the web, you should be able to see the request in the web inspector. I'm guessing the structure of https://github.com/dantoml/twentysix/blob/master/lib/twentysix/core.rb#L108-L121 changed.

**Comment by miharekar** [comment]
@dantoml no worries!

Ah, I was trying to MITM the app but they do certificate pinning so I couldn't do it simply. Didn't even think that the webapp is an SPA 🤦️

Gonna check what it's doing now

**Comment by miharekar** [comment]
Ha, they switched to graphql on https://app.n26.com/graphql

```
mutation sendSEPATransaction($pin: String!, $amount: Float!, $type: TransactionType!, $partnerBic: String, $partnerIban: String!, $partnerName: String!, $referenceText: String, $executionFrequency: FrequencyEnum, $transferDate: String, $stopDate: String) {
  sendSEPATransaction(pin: $pin, amount: $amount, type: $type, partnerBic: $partnerBic, partnerIban: $partnerIban, partnerName: $partnerName, referenceText: $referenceText, executionFrequency: $executionFrequency, transferDate: $transferDate, stopDate: $stopDate) {
    status
    errors {
      translationKey
      message
      __typename
    }
    __typename
  }
}
```

and in the variables there's a lot of "crap" which I don't think can be easily generated 😞️

If only they'd support IBAN in Siri Shortcuts…

**Comment by endocrimes** [comment]
ugh that's gonna be "fun" - all of the args look simple enough, executionFrequency and stopDate are the only two that we need to be super careful with probably 🤔

**Comment by miharekar** [comment]
Dunno, I never interacted much with graphql. I'd guess those two are for recurring transactions so maybe we can ignore them? #wishfulthinking

**Comment by miharekar** [comment]
I guess this is abandonware 😅

Closing…

**Comment by endocrimes** [comment]
Sorry! I ended up moving a lot of my day to day banking to bunq and they basically implemented all the things I automated on top of N26 😅

**Comment by miharekar** [comment]
No worries! 😅

Ah, never heard of bunq before. Gotta check it out
